#logging:
#  path: D:/java/sell/log
#  file: D:/java/sell/log/sellspring:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.132/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
wechat:
 mp-app-id: wx4b349a9cba0df9c2
 mp-app-secret: fd01380d6f7425553a063b03b6d69897